apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: consul
spec:
  rules:
  - host: consul.192.168.0.9.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: consul
          servicePort: 32005
---
kind: Service
apiVersion: v1
metadata:
  name: consul
spec:
  type: NodePort
  selector:
    app: spring-cloud-consul
  ports:
  - protocol: TCP
    port: 8500
    targetPort: 8500
    nodePort: 32005
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-cloud-consul
  labels:
    app: spring-cloud-consul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-consul
  template:
    metadata:
      labels:
        app: spring-cloud-consul
        version: latest
    spec:
      hostname: consul
      subdomain: consul
      containers:
      - name: spring-cloud-consul
        image: consul
        ports:
        - name: http
          containerPort: 8500